### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by Enjamam** [KhanhNguyen9872/xposed#2]
I've tried to install Framework and modules. But it was unable to load files from the server.

**Comment by KhanhNguyen9872** [comment]
> I've tried to install Framework and modules. But it was unable to load files from the server.

can you give me a screenshot of error, this repo only support install xposed, not modules

**Comment by Enjamam** [comment]
I think it doesn’t have support for KitKat or below.
That's why it's not working for me.
I need resources for Kit Kat.

**Comment by KhanhNguyen9872** [comment]
> I think it doesn’t have support for KitKat or below. That's why it's not working for me. I need resources for Kit Kat.

This xposed v3.1.5 isn't supported Android 4.4 or below, you must use v2.5.1 [de.robv.android.xposed.installer_2.5.1.zip](https://github.com/user-attachments/files/16823778/de.robv.android.xposed.installer_2.5.1.zip)

**Comment by Enjamam** [comment]
dl xposed failed.
It can't load the data from the server.
Could you provide anything that helps us to use Xposed in Android 4.4 and below?
I will be grateful!

**Comment by KhanhNguyen9872** [comment]
> dl xposed failed. It can't load the data from the server. Could you provide anything that helps us to use Xposed in Android 4.4 and below? I will be grateful!

i didn't have resource for sdk 20 or below, sorry you, i can't
